config/routes.rb
Rails.application.routes.draw do
  resources :orders

  get 'welcome/login'
  post 'welcome/login'
  post 'welcome/show'
  get 'welcome/index'
  get 'welcome/show'
  get 'welcome/order'
  post 'welcome/create'
  post 'sessions/signup', to: 'users#new'
  get 'sessions/signin', to: 'sessions#new'
  get 'sessions/signout', to: 'sessions#destroy', via: :delete
  post 'sessions/add_to_cart', to: 'sessions#add_to_cart'
  post 'orders/new' , to: 'orders#create'

  resources :instruments,:users,:sessions,:orders,:line_items,:carts

end

app/models/admin.rb
class Admin < ActiveRecord::Base
end

app/models/card.rb
class Card < ActiveRecord::Base
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items
	def add_instrument(instrument_id)
		current_item = line_items.find_by(instrument_id: instrument_id)
	  if current_item
		  current_item.quantity += 1
	  else
		  current_item = line_items.build(instrument_id: instrument_id)
	  end
      current_item
	end
	
	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end
end

app/models/cart_item.rb
class CartItem
    attr_reader  :instrument, :quantity
    
    def initialize(instrument)
        @instrument = instrument
        @quantity = 1
    end
    
    def increment_quantity
        @quantity +=1
    end
    
    def name
        @instrument.name
    end
    
    def price
        @instrument.price * @quantity
    end
    
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/department.rb
class Department < ActiveRecord::Base
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items
  validates_presence_of :name, :type_name, :image_url, :description, :price
  validates_numericality_of :price
  
  # 验证输入的图片地址URL合法:是否以“.gif”、“.jpg”，或“.png"其中之一结束。
  validates_format_of :image_url,
  	 :multiline => true,
  	 :with => %r{\.(gif|jpg|png)$}i,
  	 :message => 'must be a URL for GIF, JPG or PNG image.'
  		  
  # 检查价格字段的值大于0
  #validate :price_must_be_at_least_a_cent
  #protected
  #def price_must_be_at_least_a_cent
	#errors.add(:price, 'should be at least 0.01' ) if price.nil？ || price < 0.01
  #end
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  private
 # ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
	if line_items.empty?
 	  return true
 	else
 	  errors.add(:base, 'Line Items present' )
 	return false
 	end
   end
 
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :instrument
  belongs_to :cart
  belongs_to :order
  def total_price
	instrument.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :line_items
	PAYMENT_TYPES = [ "Check" , "Credit card" , "Purchase order" ]
	
	def add_line_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { |user| user.username = username.downcase }
  	before_save :create_remember_token
  	has_many :orders
 		
  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  	
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
	@cart.destroy if @cart.id == session[:cart_id]
	session[:cart_id] = nil
	redirect_to(:action =>"index", :controller=>"welcome")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params[:cart]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :register]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end
  
  def register
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :name, :sex, :uid, :phone, :email, :utype)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
	def current_cart
		#@current_cart ||= CurrentCart.set_cart
		@current_cart = Cart.find(session[:cart_id])
	rescue ActiveRecord::RecordNotFound
		@cart = Cart.create
		session[:cart_id] = @cart.id
	end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    	cookies.permanent[:remember_token] = user.remember_token
    	self.current_user = user
  	end
	def current_user=(user)
    	@current_user = user
  	end
	def current_user
    	@current_user ||= User.find_by_remember_token(cookies[:remember_token])
  	end
  	
  	def signed_in?
    	!current_user.nil?
  	end
  	
  	def sign_out
    	self.current_user = nil
    	cookies.delete(:remember_token)
  	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/_form.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
<%= stylesheet_link_tag "css"%>
<title>仪器设备管理</title>
</head>

<body>
<div class="menu">
<ul>
<li style="width:0px;"><a></a></li>
<li><a><a href="/welcome/index" class="cart">主页</a></li>
<li><a href="#" class="cart">我的购物车</a></li>
<li><a href="/welcome/order" class="cart">我的订单</a></li>
<li><a href="/instruments" class="account">仪器提供方</a></li>
<li><a class="checkout">退出</a></li>
<% if signed_in? %>
	<li style="float:right;"><a><%= link_to "我的共享", current_user %></a></li>
<% else %>
	<li style="float:right;"><a href="/instrumentShare/signin" class="login">登录</a></li>
	<li style="float:right;"><a><%= link_to '注册', new_user_path %></a></li>
<% end %>     
</ul>
</div>

<%= yield :layout %>
</body>
</html>

app/views/users/edit.html.erb
<div class="container">
<h1>修改信息</h1>
<div id="registerDiv">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :登录名 %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :密码 %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :姓名 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :性别 %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :身份证号 %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :联系电话 %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :电子邮箱 %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :用户类型 %><br>
    <%= f.text_field :utype %>
  </div>
  <div class="actions">
    <%= submit_tag "修改", :class => "submit" %> 
  </div>
<% end %>
<%= link_to '返回', users_path %>

</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>UserName</th>
      <th>Password</th>
      <th>Name</th>
      <th>Sex</th>
      <th>Id</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.name %></td>
        <td><%= user.sex %></td>
        <td><%= user.uid %></td>
        <td><%= user.phone %></td>
        <td><%= user.email %></td>
        <td><%= user.utype %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: '你确定吗?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container">
<h1>注册</h1>
<div id="registerDiv">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :登录名 %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :密码 %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :姓名 %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :性别 %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :身份证号 %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :联系电话 %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :电子邮箱 %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :用户类型 %><br>
    <%= f.text_field :utype %>
  </div>
  <div class="actions">
    <%= submit_tag "提交", :class => "submit" %> 
  </div>
<% end %>

<%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>UserName:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @user.sex %>
</p>

<p>
  <strong>Id:</strong>
  <%= @user.uid %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Type:</strong>
  <%= @user.utype %>
</p>
<%= link_to '修改信息', edit_user_path(@user) %> |
<%= link_to '返回主页', welcome_index_path %>
</div>