config/routes.rb
Rails.application.routes.draw do
  resources :orders

  get 'welcome/login'
  post 'welcome/login'
  post 'welcome/show'
  get 'welcome/index'
  get 'welcome/show'
  get 'welcome/order'
  post 'welcome/create'
  post 'sessions/signup', to: 'users#new'
  get 'sessions/signin', to: 'sessions#new'
  get 'sessions/signout', to: 'sessions#destroy', via: :delete
  post 'sessions/add_to_cart', to: 'sessions#add_to_cart'
  post 'orders/new' , to: 'orders#create'

  resources :instruments,:users,:sessions,:orders,:line_items,:carts

end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_many :line_items
  has_many :orders, through: :line_items
  validates_presence_of :name, :type_name, :image_url, :description, :price
  validates_numericality_of :price
  
  # 验证输入的图片地址URL合法:是否以“.gif”、“.jpg”，或“.png"其中之一结束。
  validates_format_of :image_url,
  	 :multiline => true,
  	 :with => %r{\.(gif|jpg|png)$}i,
  	 :message => 'must be a URL for GIF, JPG or PNG image.'
  		  
  # 检查价格字段的值大于0
  #validate :price_must_be_at_least_a_cent
  #protected
  #def price_must_be_at_least_a_cent
	#errors.add(:price, 'should be at least 0.01' ) if price.nil？ || price < 0.01
  #end
  
  before_destroy :ensure_not_referenced_by_any_line_item
  
  private
 # ensure that there are no line items referencing this product
	def ensure_not_referenced_by_any_line_item
	if line_items.empty?
 	  return true
 	else
 	  errors.add(:base, 'Line Items present' )
 	return false
 	end
   end
 
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]

  # GET /instruments
  # GET /instruments.json
  def index
    @instruments = Instrument.all
  end

  # GET /instruments/1
  # GET /instruments/1.json
  def show
  end

  # GET /instruments/new
  def new
    @instrument = Instrument.new
  end

  # GET /instruments/1/edit
  def edit
  end
  
  def register
  end

  # POST /instruments
  # POST /instruments.json
  def create
    @instrument = Instrument.new(instrument_params)

    respond_to do |format|
      if @instrument.save
        format.html { redirect_to @instrument, notice: 'Instrument was successfully created.' }
        format.json { render :show, status: :created, location: @instrument }
      else
        format.html { render :new }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instruments/1
  # PATCH/PUT /instruments/1.json
  def update
    respond_to do |format|
      if @instrument.update(instrument_params)
        format.html { redirect_to @instrument, notice: 'Instrument was successfully updated.' }
        format.json { render :show, status: :ok, location: @instrument }
      else
        format.html { render :edit }
        format.json { render json: @instrument.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instruments/1
  # DELETE /instruments/1.json
  def destroy
    @instrument.destroy
    respond_to do |format|
      format.html { redirect_to instruments_url, notice: 'Instrument was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instrument
      @instrument = Instrument.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instrument_params
      params.require(:instrument).permit(:name, :type_name, :image_url, :description, :price)
    end
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/_form.html.erb
<em><em><em><em><!DOCTYPE html></em></em></em></em>
<html lang="en" dir="ltr">

<head>
<%= stylesheet_link_tag "css"%>
<title>仪器设备管理</title>
</head>

<body>
<div class="menu">
<ul>
<li style="width:0px;"><a></a></li>
<li><a><a href="/instruments" class="cart">主页</a></li>
<li><a href="#" class="cart">我的购物车</a></li>
<li><a href="#" class="cart">我的订单</a></li>
<li class="active"><a href="#" class="account">仪器提供方</a></li>
<li><a class="checkout">退出</a></li>
<li style="float:right;"><a href="/welcome/login" class="login">登录</a></li>
<li style="float:right;"><a><%= link_to '注册', new_user_path %></a></li>     
</ul>
</div>

app/views/instruments/edit.html.erb
<h1>修改设备信息</h1>
<%= form_for(@instrument) do |f| %>
  <% if @instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
      <% @instrument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type_name %><br>
    <%= f.text_field :type_name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<%= link_to 'Show', @instrument %> |
<%= link_to 'Back', instruments_path %>

app/views/instruments/index.html.erb
<div style="width:1000px;margin: 0 auto;margin-top:10px;">
<div class="linktree">
  <span class="STYLE1">
  	<a href="#">主页</a>
  	&raquo; 
  	<a href="#">仪器设备管理</a>
  </span>
 </div>

<div id="column-left">
<div class="box">
  <div class="box-content" style="background:none;border:none;">
    <div class="box-category">
      <ul>
        <li>
                <a href="#">仪器设备管理</a>            </li>
                <li>预约交易管理<a href="#" class="active"></a>
                              <ul>
                        <li>
                            <a href="#4"> - 审核预约单</a>                                             
                        </li>
                        <li>
                            <a href="#4"> - 仪器线下授权</a>                           
                        </li>
                        <li>
                            <a href="#"> - 已结算交易 (0)</a>             
                        </li>
                      </ul>
            </li>
          </ul>
    </div>
  </div>
</div>
</div>
 
<div id="content">
  <div class="column"></div>
  <div class="product-list">
  		<!-- begin a product -->
  		<% @instruments.each do |instrument| %>
        	<div class="struct">
                	<div class="struct-right"></div>
                    <div class="struct-left"></div>
                    <div class="struct-center">
                    	<div class="line">
                            <a href="#" class="image-link">
                                <div class="image">
                                	<%= image_tag(instrument.image_url, :size => "228x228") %>                               
                            	</div>
                            </a>
                            
                            <div class="right">
                              <div class="price">￥  <%= instrument.price %></div>
                                                                
                                <div class="cart combo">
                                	<%= link_to '查看', instrument %><span class="icon icon-compare">&nbsp;</span>
                                    <%= link_to '编辑', edit_instrument_path(instrument) %><span class="icon icon-basket">&nbsp;</span>
                                    <%= link_to '删除', instrument, method: :delete, data: { confirm: '确定删除？'} %><span class="icon icon-wish">&nbsp;</span>
                                </div>
                            </div>
                            
                            <div class="name"><a href="#"><%= instrument.name + "-" + instrument.type_name %></a></div>
                            <div class="description"><%= instrument.description %></div>
                            <div class="clearfix"></div>
                        </div>
        			</div>
            </div>
        <% end %>
    	<!--end a product -->
              </div>
        <div class="clearfix"></div>
        <div class="column">
        	<div class="pagination"><div class="results">共 <%= @instruments.size() %> 台仪器</div></div>
        </div>
        <br>
        <div class="column">
        	<div class="pagination"><div class="results"><%= link_to '发布新仪器', new_instrument_path %></div></div>
        </div>
            
  </div>

</div>

<div class="icart-footer">
<div class="icart-footer-top">
	<div style="width:1000px; margin:0 auto;">	
	</div>
</div>
<div class="icart-footer-container">
  <div class="clearfix"></div>
	</div>		
	<div class="icart-footer-bottom">
		<div style="width:1000px; margin:0 auto;">				
		<div class="icart-logo-footer"></div>	
			<ul>
			<li style="float:right;padding-top:10px;list-style:none;">&copy; Copyright &copy; 2014.Leey.</li>
			</ul>		
		<div class="clearfix"></div>
		</div>
<br>
</div>
</div>

</body>
</html>

app/views/instruments/new.html.erb
<h1>上传仪器</h1>
<%= form_for(@instrument) do |f| %>
  <% if @instrument.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
      <% @instrument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type_name %><br>
    <%= f.text_field :type_name %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', instruments_path %>

app/views/instruments/show.html.erb
<div class="container">
<div id="content">
	<div class="block-white">
		<div class="block-content">
		</div>
		<div class="separator">
		</div>
		<div class="block-content">
			<div class="product-info">
				<div class="left">
					<div class="image">
						<a href="#" title="iMac">
							<%= image_tag(@instrument.image_url, :size => "228x228") %>
						</a>
					</div>
				</div>
				<div class="right">
					<div id="tabs" class="tabs">
						<a href="#tab-information" class="selected">
							
							<div>
							</div>
						</a>
						<a href="#tab-description">
							Description
						</a>
						<a href="#tab-review">
							Reviews (0)
						</a>
						<a href="#tab-related">
							Related Products (1)
						</a>
					</div>
					<div id="tab-information" class="tab-content">
						<div id="information">
						</div>
						<div class="description">
							<span>
								»&nbsp;仪器名称:
							</span>
							<a href="#">
								<%= @instrument.name %>
							</a>
							<br>
							<span>
								»&nbsp;仪器型号:
							</span>
								<%= @instrument.type_name %>
							<br>
							<span>
								»&nbsp;仪器分类:
							</span>
								<%= @instrument.itype %>
							<br>
							<span>
								»&nbsp;仪器描述:
							</span>
								<%= @instrument.description %>
						</div>
						<div class="price">
							<span class="price-new">
								$<%= @instrument.price %>
							</span>
						</div>
						<br>
						<div class="cart">
							<div>
								Qty:
								<input class="quantity" type="text" name="quantity" size="2" value="1">
								<input type="hidden" name="product_id" value="41">
								&nbsp;
								<a id="button-cart" class="button">
									
										<%= button_to "Add to Cart" %>
									
								</a>
							</div>
							<div>
								<span>
									&nbsp;&nbsp;&nbsp;- OR -&nbsp;&nbsp;&nbsp;
								</span>
							</div>
						</div>
					</div>
					<div class="price">
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>